server:
  port: 10000                                                   #设置端口
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource                #设置数据源类型
    driver-class-name: com.mysql.cj.jdbc.Driver                 #mysql驱动
    url: jdbc:mysql://localhost:3306/spring_boot_mybatis        #设置url
    username: root                                              #设置用户名
    password: root                                              #设置密码
    initialSize: 5                                              #初始化参数
    minIdle: 5                                                  #设置最少连接数
    maxActive: 20                                               #设置最大连接数
    maxWait: 60000                                              #获取连接等待超时时间
    timeBetweenEvictionRunsMillis: 60000                        #检测需要关闭的空闲连接
    minEvictableIdleTimeMillis: 300000                          #连接池最小生存时间
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: false                               #指定每个连接上PSCache的大小
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall                                          #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000 #通过connectProperties属性来打开mergeSql功能；慢SQL记录
  jpa:                                                          #是否在控制台显示sql语句
    show-sql: true
mybatis:
#  config-location: classpath:mybatis/mybatis-config.xml         #指定mybatis的配置文件
  mapper-locations: classpath:mybatis/mapper/*.xml        #指定mapper的配置文件
  type-aliases-package: com.hengyue.entity
